### PR TITLE
EPL-822: adding smithy.yml back for internal build process and associated compliance checking

### PR DESCRIPTION
**Pull request by shawnrusaw-wf**
@teresarevious-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by teresarevious-wf** [comment]
+1 to smithy addition

**Comment by teresarevious-wf** [comment]
RM +1

smithy will be running after https://jira.atl.workiva.net/browse/ATLAS-21713 is complete.

**Comment by teresarevious-wf** [comment]
+1

**Comment by colefeisthamel-wf** [comment]
RM +1 Smithy setup

**Pull request merged**
